version: '3.7'

services:
  app:
    build: .
    image: weeb-poly/syncplay-srv
    environment:
      SYNCPLAY_PASSWORD: "${SYNCPLAY_PASSWORD}"
      SYNCPLAY_SALT: "${SYNCPLAY_SALT}"
      SYNCPLAY_PORT: "${SYNCPLAY_PORT}"
      SYNCPLAY_TLS_PATH : "/app/cert"
    volumes:
      - ${SYNCPLAY_TLS_PATH}/privkey.pem:/app/cert/privkey.pem:ro
      - ${SYNCPLAY_TLS_PATH}/cert.pem:/app/cert/cert.pem:ro
      - ${SYNCPLAY_TLS_PATH}/chain.pem:/app/cert/chain.pem:ro
    ports:
      - "${SYNCPLAY_PORT}:${SYNCPLAY_PORT}"
