version: '3.7'

services:
  app:
    build: .
    image: weeb-poly/syncplay-srv
    environment:
      SYNCPLAY_PASSWORD: "${SYNCPLAY_PASSWORD}"
      SYNCPLAY_SALT: "${SYNCPLAY_SALT}"
      SYNCPLAY_PORT: "${SYNCPLAY_PORT}" 
    ports:
      - "${SYNCPLAY_PORT}:${SYNCPLAY_PORT}"
