apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: syncplay-wpi-moe
  namespace: syncplay
  labels:
    app.kubernetes.io/part-of: syncplay
spec:
  secretName: syncplay-tls-secret
  keyAlgorithm: ecdsa
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - syncplay.wpi.moe
