apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syncplay-wpi-moe
  labels:
    app.kubernetes.io/part-of: syncplay
spec:
  secretName: syncplay-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - syncplay.wpi.moe
