apiVersion: v1
kind: Service
metadata:
  name: syncplay-main
  labels:
    app.kubernetes.io/part-of: syncplay
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: syncplay
    app.kubernetes.io/component: server
  ports:
  - port: 8995
    targetPort: syncplay-tcp
    protocol: TCP
